version: "3"

services:
  db:
    image: postgres:10
  web:
    build: .
    command: python myapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db